package com.fluxplayer.app.core.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3482FF)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD8E2FF)
val onPrimaryContainerLight = Color(0xFF001A41)

val primaryLightMediumContrast = Color(0xFF0047A8)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF5B96FF)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)

val primaryLightHighContrast = Color(0xFF002052)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF205EC9)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)

val primaryDark = Color(0xFFADC6FF)
val onPrimaryDark = Color(0xFF002E6C)
val primaryContainerDark = Color(0xFF1A5FCC)
val onPrimaryContainerDark = Color(0xFFD8E2FF)

val primaryDarkMediumContrast = Color(0xFFC8D7FF)
val onPrimaryDarkMediumContrast = Color(0xFF00163D)
val primaryContainerDarkMediumContrast = Color(0xFF6B9FFF)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)

val primaryDarkHighContrast = Color(0xFFE8EEFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA3BFFF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000B1F)

val secondaryLight = Color(0xFF565E71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDAE2F9)
val onSecondaryContainerLight = Color(0xFF131C2B)

val secondaryLightMediumContrast = Color(0xFF2E3648)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6A7286)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)

val secondaryLightHighContrast = Color(0xFF1A2233)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF3D4557)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)

val secondaryDark = Color(0xFFBEC6DC)
val onSecondaryDark = Color(0xFF283041)
val secondaryContainerDark = Color(0xFF3E4759)
val onSecondaryContainerDark = Color(0xFFDAE2F9)

val secondaryDarkMediumContrast = Color(0xFFD4DBF1)
val onSecondaryDarkMediumContrast = Color(0xFF121B2B)
val secondaryContainerDarkMediumContrast = Color(0xFF8890A5)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)

val secondaryDarkHighContrast = Color(0xFFEDF1FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB4BCD1)
val onSecondaryContainerDarkHighContrast = Color(0xFF070F1E)

val tertiaryLight = Color(0xFF705574)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFAD8FD)
val onTertiaryContainerLight = Color(0xFF29132E)

val tertiaryLightMediumContrast = Color(0xFF462E4A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF846988)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)

val tertiaryLightHighContrast = Color(0xFF2B1530)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF543A58)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)

val tertiaryDark = Color(0xFFDEBCDF)
val onTertiaryDark = Color(0xFF402846)
val tertiaryContainerDark = Color(0xFF573E5C)
val onTertiaryContainerDark = Color(0xFFFAD8FD)

val tertiaryDarkMediumContrast = Color(0xFFF0D0F2)
val onTertiaryDarkMediumContrast = Color(0xFF2A132F)
val tertiaryContainerDarkMediumContrast = Color(0xFFA588A6)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)

val tertiaryDarkHighContrast = Color(0xFFFFE9FE)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFD4B3D6)
val onTertiaryContainerDarkHighContrast = Color(0xFF13001B)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA3328)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)

val errorLightHighContrast = Color(0xFF690005)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)

val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)

val backgroundLight = Color(0xFFFFFBFE)
val onBackgroundLight = Color(0xFF1A1C1E)
val surfaceLight = Color(0xFFFFFBFE)
val onSurfaceLight = Color(0xFF1A1C1E)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF43474F)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC4C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3033)
val inverseOnSurfaceLight = Color(0xFFF0F0F4)
val inversePrimaryLight = Color(0xFFADC6FF)
val surfaceDimLight = Color(0xFFDADBE1)
val surfaceBrightLight = Color(0xFFFFFBFE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F5FA)
val surfaceContainerLight = Color(0xFFEEEFF5)
val surfaceContainerHighLight = Color(0xFFE9EAEF)
val surfaceContainerHighestLight = Color(0xFFE3E4E9)

val backgroundLightMediumContrast = Color(0xFFFFFBFE)
val onBackgroundLightMediumContrast = Color(0xFF1A1C1E)
val surfaceLightMediumContrast = Color(0xFFFFFBFE)
val onSurfaceLightMediumContrast = Color(0xFF141618)
val surfaceVariantLightMediumContrast = Color(0xFFE1E2EC)
val onSurfaceVariantLightMediumContrast = Color(0xFF353940)
val outlineLightMediumContrast = Color(0xFF51545C)
val outlineVariantLightMediumContrast = Color(0xFF6D7078)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2F3033)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F4)
val inversePrimaryLightMediumContrast = Color(0xFFADC6FF)
val surfaceDimLightMediumContrast = Color(0xFFDADBE1)
val surfaceBrightLightMediumContrast = Color(0xFFFFFBFE)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF4F5FA)
val surfaceContainerLightMediumContrast = Color(0xFFE9EAEF)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFE0E5)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD4D6DB)

val backgroundLightHighContrast = Color(0xFFFFFBFE)
val onBackgroundLightHighContrast = Color(0xFF1A1C1E)
val surfaceLightHighContrast = Color(0xFFFFFBFE)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE1E2EC)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF272A31)
val outlineVariantLightHighContrast = Color(0xFF43474F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F3033)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF3C6EC8)
val surfaceDimLightHighContrast = Color(0xFFDADBE1)
val surfaceBrightLightHighContrast = Color(0xFFFFFBFE)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF0F0F4)
val surfaceContainerLightHighContrast = Color(0xFFE1E2E7)
val surfaceContainerHighLightHighContrast = Color(0xFFD6D7DC)
val surfaceContainerHighestLightHighContrast = Color(0xFFC4C6D0)

val backgroundDark = Color(0xFF0D0D12)
val onBackgroundDark = Color(0xFFE3E4E9)
val surfaceDark = Color(0xFF0D0D12)
val onSurfaceDark = Color(0xFFE3E4E9)
val surfaceVariantDark = Color(0xFF43474F)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8D9098)
val outlineVariantDark = Color(0xFF43474F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E4E9)
val inverseOnSurfaceDark = Color(0xFF2F3033)
val inversePrimaryDark = Color(0xFF3482FF)
val surfaceDimDark = Color(0xFF0D0D12)
val surfaceBrightDark = Color(0xFF3C3D42)
val surfaceContainerLowestDark = Color(0xFF08080D)
val surfaceContainerLowDark = Color(0xFF15161B)
val surfaceContainerDark = Color(0xFF191A1F)
val surfaceContainerHighDark = Color(0xFF24252A)
val surfaceContainerHighestDark = Color(0xFF2F3035)

val backgroundDarkMediumContrast = Color(0xFF0D0D12)
val onBackgroundDarkMediumContrast = Color(0xFFE3E4E9)
val surfaceDarkMediumContrast = Color(0xFF0D0D12)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF43474F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDDDFE8)
val outlineDarkMediumContrast = Color(0xFFAFB2BB)
val outlineVariantDarkMediumContrast = Color(0xFF8D9098)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE3E4E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF24252A)
val inversePrimaryDarkMediumContrast = Color(0xFF1464D2)
val surfaceDimDarkMediumContrast = Color(0xFF0D0D12)
val surfaceBrightDarkMediumContrast = Color(0xFF47484D)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF030308)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191A1F)
val surfaceContainerDarkMediumContrast = Color(0xFF212227)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2C2D32)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF37383D)

val backgroundDarkHighContrast = Color(0xFF0D0D12)
val onBackgroundDarkHighContrast = Color(0xFFE3E4E9)
val surfaceDarkHighContrast = Color(0xFF0D0D12)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF43474F)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFDDDFE8)
val outlineVariantDarkHighContrast = Color(0xFFAFB2BB)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE3E4E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF00348C)
val surfaceDimDarkHighContrast = Color(0xFF0D0D12)
val surfaceBrightDarkHighContrast = Color(0xFF525358)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF15161B)
val surfaceContainerDarkHighContrast = Color(0xFF202126)
val surfaceContainerHighDarkHighContrast = Color(0xFF2B2C31)
val surfaceContainerHighestDarkHighContrast = Color(0xFF36373C)

val backgroundPureBlack = Color(0xFF000000)
val surfacePureBlack = Color(0xFF000000)
val surfaceDimPureBlack = Color(0xFF000000)
val surfaceBrightPureBlack = Color(0xFF1A1A1A)
val surfaceContainerLowestPureBlack = Color(0xFF000000)
val surfaceContainerLowPureBlack = Color(0xFF0A0A0A)
val surfaceContainerPureBlack = Color(0xFF121212)
val surfaceContainerHighPureBlack = Color(0xFF1A1A1A)
val surfaceContainerHighestPureBlack = Color(0xFF222222)

val seed = Color(0xFF3482FF)